# Generated by Django 4.1.2 on 2022-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('confirmpassword', models.CharField(max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-email'],
            },
        ),
    ]
